### ISSUE TITLE
Input data from plasmid library sequencing for screen_dynamics.py

### ISSUE THREAD

**Issue by dburkhardt** [epigen/crop-seq#2]
Hello, I'm trying to recreate the plot in Figure 2B of your paper using the function screen_dynamics.py, but I can't find the input data in the supplementary files or at the GEO accession. Can you please point me towards it?

Thank you for putting all of your code online!

**Comment by afrendeiro** [comment]
Hi Daniel! Thanks for the interest and for pointing this out!
You can find these data here: http://www.medical-epigenomics.org/papers/datlinger2017/data/gRNA_counts/
