### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by LJK1991** [epigen/crop-seq#4]
Hello,
I'm trying to perform some test runs with your pipeline as soon i will have to do it on my own cropseq data. However i'm getting this error.

`python src/guides_to_ref.py
Traceback (most recent call last):
  File "src/guides_to_ref.py", line 3, in <module>
    from looper.models import Project
ModuleNotFoundError: No module named 'looper.models'
Makefile:7: recipe for target 'makeref' failed
make: *** [makeref] Error 1
`
i have the latest version of looper where there is no project.py. However if i ignore the line i get this error.

`python src/guides_to_ref.py
Traceback (most recent call last):
  File "src/guides_to_ref.py", line 58, in <module>
    prj = Project(os.path.join("metadata", "config.yaml"))
NameError: name 'Project' is not defined
Makefile:7: recipe for target 'makeref' failed
make: *** [makeref] Error 1
`
now i've tried using the older 0.7.2 version but there i get into some more issues and was hoping that there might be a simper solution from the start.
thank you in advance.

Regards,
Lucas Kuijpers
PhD student

**Comment by afrendeiro** [comment]
Hi Lukas,

The models of `looper` have moved to their own package called `peppy`(https://github.com/pepkit/peppy/).

So if you want to run a more recent software stack, you can simply `pip install peppy` and replace `from looper.models import Project` with `from peppy import Project` here: https://github.com/epigen/crop-seq/blob/master/src/guides_to_ref.py#L3

Hope that helps, Andre

**Comment by LJK1991** [comment]
this works thank you!

**Comment by LJK1991** [comment]
Hey Andre,

Another similar question.
I'm running the make process of Cropseq now with the open_pipelines
Dropseq.py pipeline. However, here it cant import the AttributeDict from
peppy package. I checked and my peppy is up to date and i cant find the
function in the documentations. i tried changing it to he
collections.attributedict package, but that doesnt work. it seems to be in
more of the pipelines. I hope i'm not bothering you too much. Thank you in
advance.

Kind regards,
Lucas Kuijpers

**Comment by afrendeiro** [comment]
Hi Lukas,

The `looper` program was split into some parts. The biologically oriented models are now part of `peppy` but some of the more abstract classes were moved into the `attmap` package (https://github.com/pepkit/attmap).
Please install it with:
```bash
pip install attmap
```

and import it with:
```python
from attmap import AttributeDict
```
